/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * AnimalInsert.java
 *
 * Created on 29-Apr-2014, 20:24:08
 */

package CombinedProjectPackage;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import inheritance_folder.Animal;


/**
 *
 * @author MF-Laptop
 */
public class AnimalInsert extends javax.swing.JFrame {

    private PreparedStatement prest;

    /** Creates new form AnimalInsert */
    public AnimalInsert() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        AnimalID = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        Space = new javax.swing.JTextField();
        AnimalName = new javax.swing.JTextField();
        Type = new javax.swing.JTextField();
        Gender = new javax.swing.JTextField();
        DOB = new javax.swing.JTextField();
        DietType = new javax.swing.JTextField();
        Diet = new javax.swing.JTextField();
        Status = new javax.swing.JTextField();
        Health = new javax.swing.JTextField();
        OK = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setText("Animal ID");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 10, 90, 14);

        AnimalID.setText("MAM111");
        AnimalID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AnimalIDActionPerformed(evt);
            }
        });
        getContentPane().add(AnimalID);
        AnimalID.setBounds(110, 10, 100, 20);

        jLabel2.setText("Animal Name");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(10, 40, 100, 14);

        jLabel3.setText("Type");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(10, 70, 100, 14);

        jLabel4.setText("Gender");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(10, 100, 100, 14);

        jLabel5.setText("DOB");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(10, 130, 100, 14);

        jLabel6.setText("Status");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(220, 70, 60, 14);

        jLabel8.setText("Diet");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(220, 40, 70, 20);

        jLabel10.setText("Diet type");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(220, 10, 70, 14);

        jLabel9.setText("Health");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(220, 100, 70, 20);

        jLabel11.setText("Req Space");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(220, 130, 80, 20);

        Space.setText("1");
        getContentPane().add(Space);
        Space.setBounds(300, 130, 110, 20);

        AnimalName.setText("LION");
        getContentPane().add(AnimalName);
        AnimalName.setBounds(110, 40, 100, 20);

        Type.setText("MAMMAL");
        getContentPane().add(Type);
        Type.setBounds(110, 70, 100, 20);

        Gender.setText("MALE");
        getContentPane().add(Gender);
        Gender.setBounds(110, 100, 100, 20);

        DOB.setText("1992-12-12");
        getContentPane().add(DOB);
        DOB.setBounds(110, 130, 100, 20);

        DietType.setText("CARNIVORE");
        getContentPane().add(DietType);
        DietType.setBounds(300, 10, 110, 20);

        Diet.setText("RED MEAT");
        getContentPane().add(Diet);
        Diet.setBounds(300, 40, 110, 20);

        Status.setText("GOOD");
        getContentPane().add(Status);
        Status.setBounds(300, 70, 110, 20);

        Health.setText("HEALTHY");
        getContentPane().add(Health);
        Health.setBounds(300, 100, 110, 20);

        OK.setText("Insert an animal");
        OK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OKActionPerformed(evt);
            }
        });
        getContentPane().add(OK);
        OK.setBounds(10, 180, 210, 23);

        jButton1.setText("Main menu");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(230, 180, 190, 23);

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-445)/2, (screenSize.height-276)/2, 445, 276);
    }// </editor-fold>//GEN-END:initComponents

    private void AnimalIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AnimalIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AnimalIDActionPerformed

    private void OKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OKActionPerformed
        String url = "jdbc:mysql://127.0.0.1:3306/";
        String dbName = "dublinzoo";
        String driver = "com.mysql.jdbc.Driver";
        String userName = "root";
        String password = "nss2013";//"NSS2014";

        try{
        Animal A = new Animal();

        A.setAnimal_ID(AnimalID.getText());
        A.setAnimal_Name(AnimalName.getText());
        A.setAnimal_Type(Type.getText());
        A.setGender(Gender.getText());
        A.setDOB(DOB.getText());
        A.setDiet_Type(DietType.getText());
        A.setDiet(Diet.getText());
        A.setStatus(Status.getText());
        A.setHealth(Health.getText());
        A.setSpace_Required_Acres(Integer.parseInt(Space.getText()));

        Class.forName(driver).newInstance();
        System.out.println("Connection to database" + dbName + "...");
        Connection conn = (Connection) DriverManager.getConnection(url+dbName,userName,password);
        System.out.println("Connected database succesfully...");

        String sql = "INSERT INTO animal (ANIMAL_ID,ANIMAL_NAME,ANIMAL_TYPE,GENDER," +
                "DOB,DIET_TYPE,DIET,STATUS,HEALTH,SPACE_REQUIRED_ACRES)" +
                "VALUES(?,?,?,?,?,?,?,?,?,?)";

        prest = conn.prepareStatement(sql);

        prest.setString(1, A.getAnimal_ID());
        prest.setString(2, A.getAnimal_Name());
        prest.setString(3, A.getAnimal_Type());
        prest.setString(4, A.getGender());
        prest.setString(5, A.getDOB());
        prest.setString(6, A.getDiet_Type());
        prest.setString(7, A.getDiet());
        prest.setString(8, A.getStatus());
        prest.setString(9, A.getHealth());
        prest.setInt(10, A.getSpace_Required_Acres());
        
        prest.execute();

        conn.close();

        }catch (Exception e){
        e.printStackTrace();
        }



    }//GEN-LAST:event_OKActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        ManagerFrame Frame1= new ManagerFrame ();
        Frame1.setVisible(true);

        setVisible(false);//this line and the one below close the login form.
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AnimalInsert().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AnimalID;
    private javax.swing.JTextField AnimalName;
    private javax.swing.JTextField DOB;
    private javax.swing.JTextField Diet;
    private javax.swing.JTextField DietType;
    private javax.swing.JTextField Gender;
    private javax.swing.JTextField Health;
    private javax.swing.JButton OK;
    private javax.swing.JTextField Space;
    private javax.swing.JTextField Status;
    private javax.swing.JTextField Type;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables

}
