/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * SearchAnimal.java
 *
 * Created on 29-Apr-2014, 22:47:45
 */

package CombinedProjectPackage;

import inheritance_folder.Animal;
import inheritance_folder.Feeding;
import inheritance_folder.Manager;
import inheritance_folder.Staff;
import inheritance_folder.Vet;
import com.mysql.jdbc.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author MF-Laptop
 */
public class SearchAnimal extends javax.swing.JFrame {

    private PreparedStatement prest;
    Animal A = new Animal();
    Staff S = new Staff();
    Manager M = new Manager();
    Vet V = new Vet();
    Feeding F = new Feeding();

    /** Creates new form SearchAnimal */
    public SearchAnimal() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        AnimalSearchTable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        AnimalSCB1 = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        AnimalSearch = new javax.swing.JButton();
        AnimalIDSearch = new javax.swing.JTextField();
        Update = new javax.swing.JButton();
        Delete = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        SearchName = new javax.swing.JTextField();
        SearchGender = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        AnimalSearchTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        AnimalSearchTable.setFillsViewportHeight(true);
        jScrollPane1.setViewportView(AnimalSearchTable);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(10, 190, 800, 150);

        jLabel1.setText("Choose Table");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 20, 110, 30);

        AnimalSCB1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "animal", "habitat", "staff", "records", "general staff", "manager", "vet" }));
        AnimalSCB1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                AnimalSCB1KeyPressed(evt);
            }
        });
        getContentPane().add(AnimalSCB1);
        AnimalSCB1.setBounds(110, 20, 140, 30);

        jLabel3.setText("Search by ID");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(260, 20, 150, 30);

        AnimalSearch.setText("Search");
        AnimalSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AnimalSearchActionPerformed(evt);
            }
        });
        getContentPane().add(AnimalSearch);
        AnimalSearch.setBounds(580, 20, 180, 29);

        AnimalIDSearch.setText("MAM101");
        AnimalIDSearch.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                AnimalIDSearchFocusGained(evt);
            }
        });
        getContentPane().add(AnimalIDSearch);
        AnimalIDSearch.setBounds(410, 20, 130, 30);

        Update.setText("Update");
        Update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateActionPerformed(evt);
            }
        });
        getContentPane().add(Update);
        Update.setBounds(580, 60, 180, 29);

        Delete.setText("Delete");
        Delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteActionPerformed(evt);
            }
        });
        getContentPane().add(Delete);
        Delete.setBounds(580, 100, 180, 29);

        jLabel2.setText("Search by Name");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(260, 60, 150, 30);

        jLabel4.setText("Search by Gender");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(260, 100, 150, 30);

        SearchName.setText("LION");
        SearchName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                SearchNameFocusGained(evt);
            }
        });
        getContentPane().add(SearchName);
        SearchName.setBounds(410, 60, 130, 26);

        SearchGender.setText("MALE");
        SearchGender.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                SearchGenderFocusGained(evt);
            }
        });
        getContentPane().add(SearchGender);
        SearchGender.setBounds(410, 100, 130, 26);

        jButton1.setText("Logout");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(580, 150, 180, 29);

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-836)/2, (screenSize.height-416)/2, 836, 416);
    }// </editor-fold>//GEN-END:initComponents

    private void AnimalSCB1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_AnimalSCB1KeyPressed
        
    if (evt.getKeyCode()==java.awt.event.KeyEvent.VK_ENTER)

{
    if (AnimalSCB1.getSelectedItem().equals("animal"))
    {
    AnimalIDSearch.setVisible(true);
        SearchName.setVisible(true);
        SearchGender.setVisible(true);
        jLabel3.setVisible(true);
        jLabel2.setVisible(true);
        jLabel4.setVisible(true);
    
    }
    else if (AnimalSCB1.getSelectedItem().equals("habitat"))
    {
    AnimalIDSearch.setVisible(true);
        SearchName.setVisible(true);
        SearchGender.setVisible(true);
        jLabel3.setVisible(true);
        jLabel2.setVisible(true);
        jLabel4.setVisible(true);
    }
    else if (AnimalSCB1.getSelectedItem().equals("staff"))
    {
    AnimalIDSearch.setVisible(true);
        SearchName.setVisible(true);
        SearchGender.setVisible(true);
        jLabel3.setVisible(true);
        jLabel2.setVisible(true);
        jLabel4.setVisible(true);
   
    }
    else if (AnimalSCB1.getSelectedItem().equals("records"))
    {
    AnimalIDSearch.setVisible(true);
        SearchName.setVisible(true);
        SearchGender.setVisible(true);
        jLabel3.setVisible(true);
        jLabel2.setVisible(true);
        jLabel4.setVisible(true);
    
    }
    else if (AnimalSCB1.getSelectedItem().equals("feeding staff"))
    {
    AnimalIDSearch.setVisible(true);
        SearchName.setVisible(true);
        SearchGender.setVisible(true);
        jLabel3.setVisible(true);
        jLabel2.setVisible(true);
        jLabel4.setVisible(true);
    
    }
    else if (AnimalSCB1.getSelectedItem().equals("manager"))
    {
    AnimalIDSearch.setVisible(true);
        SearchName.setVisible(true);
        SearchGender.setVisible(true);
        jLabel3.setVisible(true);
        jLabel2.setVisible(true);
        jLabel4.setVisible(true);
    
    }
    else if (AnimalSCB1.getSelectedItem().equals("vet"))
    {
    AnimalIDSearch.setVisible(true);
        SearchName.setVisible(true);
        SearchGender.setVisible(true);
        jLabel3.setVisible(true);
        jLabel2.setVisible(true);
        jLabel4.setVisible(true);
    
    }
    
}

    }//GEN-LAST:event_AnimalSCB1KeyPressed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        AnimalIDSearch.setVisible(false);
        SearchName.setVisible(false);
        SearchGender.setVisible(false);
        jLabel3.setVisible(false);
        jLabel2.setVisible(false);
        jLabel4.setVisible(false);
    }//GEN-LAST:event_formWindowOpened

    private void AnimalSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AnimalSearchActionPerformed
          String url = "jdbc:mysql://127.0.0.1:3306/";
          String dbName = "dublinzoo";
          String driver = "com.mysql.jdbc.Driver";
          String userName = "root";
          //String password = "NSS2013";
          String password = "nss2013";
          //String password = "NSS2014";

          if (AnimalSCB1.getSelectedItem().equals("animal"))
          {
          try
          {
                Class.forName(driver).newInstance();
                Connection conn = (Connection) DriverManager.getConnection(url + dbName, userName, password);
                System.out.println("Database Connection Successful");
                // Set Up SQL
                String sql1 = "SELECT * FROM dublinzoo.animal WHERE ANIMAL_ID LIKE ?";

                //String sql2 = "SELECT * FROM dublinzoo.animal WHERE ANIMAL_NAME LIKE ?";

                //String sql3 = "SELECT * FROM dublinzoo.animal WHERE GENDER LIKE ?";
                // Excute Query and send result set to rs
                prest = conn.prepareStatement(sql1);
                //prest = conn.prepareStatement(sql2);
                //prest = conn.prepareStatement(sql3);
                
                prest.setString(1,AnimalIDSearch.getText());
                //prest.setString(2,SearchName.getText());
                //prest.setString(3,SearchGender.getText());

                ResultSet rs = prest.executeQuery();
                //Retrieve by column name
                AnimalSearchTable.setModel(DbUtils.resultSetToTableModel(rs));
                rs.close();
                prest.close();
                // Close the connection to the database
                conn.close();
                }
                catch (Exception e)
                {
                e.printStackTrace();
                }
                }

          if (AnimalSCB1.getSelectedItem().equals("habitat"))
                {
                try
                {
                Class.forName(driver).newInstance();
                Connection conn = (Connection) DriverManager.getConnection(url + dbName, userName, password);
                System.out.println("Database Connection Successful");
                // Set Up SQL
                String sql = "SELECT * FROM dublinzoo.habitat WHERE AREA_ID LIKE ?";
                // Excute Query and send result set to rs
                prest = conn.prepareStatement(sql);
                prest.setString(1,AnimalIDSearch.getText());
                ResultSet rs = prest.executeQuery();
                //Retrieve by column name
                AnimalSearchTable.setModel(DbUtils.resultSetToTableModel(rs));
                rs.close();
                prest.close();
                // Close the connection to the database
                conn.close();
                }
                catch (Exception e)
                {
                e.printStackTrace();
                }
                }

          if (AnimalSCB1.getSelectedItem().equals("staff"))
                {
                try
                {
                Class.forName(driver).newInstance();
                Connection conn = (Connection) DriverManager.getConnection(url + dbName, userName, password);
                System.out.println("Database Connection Successful");
                // Set Up SQL
                String sql = "SELECT * FROM dublinzoo.staff WHERE STAFF_ID LIKE ?";
                // Excute Query and send result set to rs
                prest = conn.prepareStatement(sql);
                prest.setString(1,AnimalIDSearch.getText());
                ResultSet rs = prest.executeQuery();
                //Retrieve by column name
                AnimalSearchTable.setModel(DbUtils.resultSetToTableModel(rs));
                rs.close();
                prest.close();
                // Close the connection to the database
                conn.close();
                }
                catch (Exception e)
                {
                e.printStackTrace();
                }
                }

                if (AnimalSCB1.getSelectedItem().equals("records"))
                {
                try
                {
                Class.forName(driver).newInstance();
                Connection conn = (Connection) DriverManager.getConnection(url + dbName, userName, password);
                System.out.println("Database Connection Successful");
                // Set Up SQL
                String sql = "SELECT * FROM dublinzoo.records WHERE RECORD_ID LIKE ?";
                // Excute Query and send result set to rs
                prest = conn.prepareStatement(sql);
                prest.setString(1,AnimalIDSearch.getText());
                ResultSet rs = prest.executeQuery();
                //Retrieve by column name
                AnimalSearchTable.setModel(DbUtils.resultSetToTableModel(rs));
                rs.close();
                prest.close();
                // Close the connection to the database
                conn.close();
                }
                catch (Exception e)
                {
                e.printStackTrace();
                }
                }

                if (AnimalSCB1.getSelectedItem().equals("general staff"))
                {
                try
                {
                Class.forName(driver).newInstance();
                Connection conn = (Connection) DriverManager.getConnection(url + dbName, userName, password);
                System.out.println("Database Connection Successful");
                // Set Up SQL
                String sql = "SELECT * FROM dublinzoo.general_staff WHERE GENERAL_STAFF_ID LIKE ?";
                // Excute Query and send result set to rs
                prest = conn.prepareStatement(sql);
                prest.setString(1,AnimalIDSearch.getText());
                ResultSet rs = prest.executeQuery();
                //Retrieve by column name
                AnimalSearchTable.setModel(DbUtils.resultSetToTableModel(rs));
                rs.close();
                prest.close();
                // Close the connection to the database
                conn.close();
                }
                catch (Exception e)
                {
                e.printStackTrace();
                }
                }

                if (AnimalSCB1.getSelectedItem().equals("manager"))
                {
                try
                {
                Class.forName(driver).newInstance();
                Connection conn = (Connection) DriverManager.getConnection(url + dbName, userName, password);
                System.out.println("Database Connection Successful");
                // Set Up SQL
                String sql = "SELECT * FROM dublinzoo.manager WHERE MANAGER_ID LIKE ?";
                // Excute Query and send result set to rs
                prest = conn.prepareStatement(sql);
                prest.setString(1,AnimalIDSearch.getText());
                ResultSet rs = prest.executeQuery();
                //Retrieve by column name
                AnimalSearchTable.setModel(DbUtils.resultSetToTableModel(rs));
                rs.close();
                prest.close();
                // Close the connection to the database
                conn.close();
                }
                catch (Exception e)
                {
                e.printStackTrace();
                }
                }

                if (AnimalSCB1.getSelectedItem().equals("vet"))
                {
                try
                {
                Class.forName(driver).newInstance();
                Connection conn = (Connection) DriverManager.getConnection(url + dbName, userName, password);
                System.out.println("Database Connection Successful");
                // Set Up SQL
                String sql = "SELECT * FROM dublinzoo.vet WHERE VET_ID LIKE ?";
                // Excute Query and send result set to rs
                prest = conn.prepareStatement(sql);
                prest.setString(1,AnimalIDSearch.getText());
                ResultSet rs = prest.executeQuery();
                //Retrieve by column name
                AnimalSearchTable.setModel(DbUtils.resultSetToTableModel(rs));
                rs.close();
                prest.close();
                // Close the connection to the database
                conn.close();
                }
                catch (Exception e)
                {
                e.printStackTrace();
                }
                }

    }//GEN-LAST:event_AnimalSearchActionPerformed

    private void UpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateActionPerformed

          String url = "jdbc:mysql://127.0.0.1:3306/";
          String dbName = "dublinzoo";
          String driver = "com.mysql.jdbc.Driver";
          String userName = "root";
          String password = "nss2013";
          //String password = "NSS2014";

          if (AnimalSCB1.getSelectedItem().equals("animal"))
          {
          try
          {
          Class.forName(driver).newInstance();
          Connection conn = (Connection) DriverManager.getConnection(url + dbName, userName, password);
          System.out.println("Database Connection Successful");

          // Set Up SQL
          String sql = " UPDATE dublinzoo.animal set ANIMAL_NAME = ?, ANIMAL_TYPE = ?, "
                    + " GENDER = ?, DOB = ?, DIET_TYPE = ?, DIET = ?, STATUS = ?, HEALTH= ?, "
                    +" SPACE_REQUIRED_ACRES = ? WHERE ANIMAL_ID = ? ";
     
         A.setAnimal_Name(AnimalSearchTable.getValueAt(0, 1).toString());
         A.setAnimal_Type(AnimalSearchTable.getValueAt(0, 2).toString());
         A.setGender(AnimalSearchTable.getValueAt(0, 3).toString());
         A.setDOB(AnimalSearchTable.getValueAt(0, 4).toString());
         A.setDiet_Type(AnimalSearchTable.getValueAt(0, 5).toString());
         A.setDiet(AnimalSearchTable.getValueAt(0, 6).toString());
         A.setStatus(AnimalSearchTable.getValueAt(0, 7).toString());
         A.setHealth(AnimalSearchTable.getValueAt(0, 8).toString());
         A.setSpace_Required_Acres(Integer.parseInt(AnimalSearchTable.getValueAt(0, 9).toString()));

          // Excute Query and send result set to rs
          prest = conn.prepareStatement(sql);
          
          prest.setString(1, A.getAnimal_Name());
          prest.setString(2, A.getAnimal_Type());
          prest.setString(3, A.getGender());
          prest.setString(4, A.getDOB());
          prest.setString(5, A.getDiet_Type());
          prest.setString(6, A.getDiet());
          prest.setString(7, A.getStatus());
          prest.setString(8, A.getHealth());
          prest.setInt(9, A.getSpace_Required_Acres());
          prest.setString(10, AnimalIDSearch.getText());
          

          prest.executeUpdate();
          JOptionPane.showMessageDialog(rootPane, "Update Successfull!");

          // Close the connection to the database
          conn.close();
          prest.close();
          }
          
          //catch (SQLException s)
          //{
          //System.out.println("SQL statement is not executed!");
          //JOptionPane.showMessageDialog(rootPane, "Update NOT Successfull!");
          //}


          catch (Exception e)
          {
          e.printStackTrace();
          }
          }

if (AnimalSCB1.getSelectedItem().equals("staff"))
          {
          try
          {
          Class.forName(driver).newInstance();
          Connection conn = (Connection) DriverManager.getConnection(url + dbName, userName, password);
          System.out.println("Database Connection Successful");

          // Set Up SQL
          String sql = " UPDATE dublinzoo.staff set NAME = ?, GENDER = ?, PPS_NUMBER = ? "
                    + "DOB = ?, START_OF_EMPLOYMENT = ?, ADDRESS = ?, CONTACT_NUMBER = ?, EMAIL= ?, "
                    +" SALARY = ?";



        

        S.setName(AnimalSearchTable.getValueAt(0, 1).toString());
        S.setGender(AnimalSearchTable.getValueAt(0, 2).toString());
        S.setPPS_no(AnimalSearchTable.getValueAt(0, 3).toString());
        S.setDOB(AnimalSearchTable.getValueAt(0, 4).toString());
        S.setStart_of_Employment(AnimalSearchTable.getValueAt(0, 5).toString());
        S.setAddress(AnimalSearchTable.getValueAt(0, 6).toString());
        S.setContact_Number(Integer.parseInt(AnimalSearchTable.getValueAt(0, 7).toString()));
        S.setEmail(AnimalSearchTable.getValueAt(0, 8).toString());
        S.setSalary(Double.parseDouble(AnimalSearchTable.getValueAt(0, 9).toString()));

          // Excute Query and send result set to rs
          prest = conn.prepareStatement(sql);



          prest.setString(1, S.getName());
          prest.setString(2, S.getGender());
          prest.setString(3, S.getPPS_no());
          prest.setString(4, S.getDOB());
          prest.setString(5, S.getStart_of_Employment());
          prest.setString(6, S.getAddress());
          prest.setInt(7, S.getContact_Number());
          prest.setString(8, S.getEmail());
          prest.setDouble(9, S.getSalary());
          prest.setString(10, AnimalIDSearch.getText());


          prest.executeUpdate();
          JOptionPane.showMessageDialog(rootPane, "Update Successfull!");

          // Close the connection to the database
          conn.close();
          prest.close();
          }

          //catch (SQLException s)
          //{
          //System.out.println("SQL statement is not executed!");
          //JOptionPane.showMessageDialog(rootPane, "Update NOT Successfull!");
          //}

          catch (Exception e)
          {
          e.printStackTrace();
          }
          }


    }//GEN-LAST:event_UpdateActionPerformed

    private void DeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteActionPerformed

          String url = "jdbc:mysql://127.0.0.1:3306/";
          String dbName = "dublinzoo";
          String driver = "com.mysql.jdbc.Driver";
          String userName = "root";
          String password = "nss2013";
          //String password = "NSS2014";
          try

       {
            Class.forName(driver).newInstance();
            Connection conn = (Connection) DriverManager.getConnection(url + dbName, userName, password);
            System.out.println("Database Connection Successful");

            String sql = "DELETE FROM animal WHERE ANIMAL_ID = ?";

            A.setAnimal_ID(AnimalSearchTable.getValueAt(0, 0).toString());
            prest = conn.prepareStatement(sql);
            prest.setString(1, A.getAnimal_ID());
            prest.executeUpdate();

            JOptionPane.showMessageDialog(null, "Record has been successfully deleted");

            prest.close();
            conn.close();

       }
        catch (Exception e)
        {
        e.printStackTrace();
        }
    }//GEN-LAST:event_DeleteActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        ManagerFrame Frame1= new ManagerFrame ();
        Frame1.setVisible(true);

        setVisible(false);//this line and the one below close the login form.
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void AnimalIDSearchFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_AnimalIDSearchFocusGained

        SearchName.setEditable(false);
        SearchGender.setEditable(false);
    }//GEN-LAST:event_AnimalIDSearchFocusGained

    private void SearchNameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_SearchNameFocusGained
        AnimalIDSearch.setEditable(false);
        SearchGender.setEditable(false);
    }//GEN-LAST:event_SearchNameFocusGained

    private void SearchGenderFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_SearchGenderFocusGained
        AnimalIDSearch.setEditable(false);
        SearchGender.setEditable(false);
    }//GEN-LAST:event_SearchGenderFocusGained

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SearchAnimal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AnimalIDSearch;
    private javax.swing.JComboBox AnimalSCB1;
    private javax.swing.JButton AnimalSearch;
    private javax.swing.JTable AnimalSearchTable;
    private javax.swing.JButton Delete;
    private javax.swing.JTextField SearchGender;
    private javax.swing.JTextField SearchName;
    private javax.swing.JButton Update;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

}
