/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * VetFrame.java
 *
 * Created on 20-Mar-2014, 15:44:09
 */

package CombinedProjectPackage;

import inheritance_folder.Animal;
import com.mysql.jdbc.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author fennell.38261
 */
public class VetFrame extends javax.swing.JFrame {

    private PreparedStatement prest;
    Animal A = new Animal();
    /** Creates new form VetFrame */
    public VetFrame() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        VetTable = new javax.swing.JTable();
        VetSearch = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        VetCBox1 = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        VetIDSearch = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(null);

        VetTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(VetTable);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(10, 110, 710, 260);

        VetSearch.setText("Search");
        VetSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VetSearchActionPerformed(evt);
            }
        });
        getContentPane().add(VetSearch);
        VetSearch.setBounds(20, 400, 65, 23);

        jButton2.setText("Update");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(100, 400, 67, 23);

        VetCBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "------------------", "animal", "records" }));
        VetCBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VetCBox1ActionPerformed(evt);
            }
        });
        VetCBox1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                VetCBox1KeyPressed(evt);
            }
        });
        getContentPane().add(VetCBox1);
        VetCBox1.setBounds(20, 10, 160, 20);

        jLabel1.setText("Search by ID");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(190, 10, 100, 30);
        getContentPane().add(VetIDSearch);
        VetIDSearch.setBounds(290, 10, 100, 20);

        jButton1.setText("Logout");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(190, 400, 65, 23);

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-754)/2, (screenSize.height-471)/2, 754, 471);
    }// </editor-fold>//GEN-END:initComponents

    private void VetCBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VetCBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_VetCBox1ActionPerformed

    private void VetSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VetSearchActionPerformed

          String url = "jdbc:mysql://127.0.0.1:3306/";
          String dbName = "dublinzoo";
          String driver = "com.mysql.jdbc.Driver";
          String userName = "root";
          //String password = "NSS2013";
          String password = "nss2013";
          //String password = "NSS2014";


          if (VetCBox1.getSelectedItem().equals("animal"))
          {
          try
          {
                Class.forName(driver).newInstance();
                Connection conn = (Connection) DriverManager.getConnection(url + dbName, userName, password);
                System.out.println("Database Connection Successful");

                // Set Up SQL
                String sql = "SELECT * FROM dublinzoo.animal WHERE ANIMAL_ID LIKE ?";

                // Excute Query and send result set to rs
                prest = conn.prepareStatement(sql);
                prest.setString(1,VetIDSearch.getText());

                ResultSet rs = prest.executeQuery();

                //Retrieve by column name
                VetTable.setModel(DbUtils.resultSetToTableModel(rs));

                rs.close();
                prest.close();

                // Close the connection to the database
                conn.close();
            }
                catch (Exception e)
                {
                e.printStackTrace();
                }
            }

          else if (VetCBox1.getSelectedItem().equals("records"))
          {
          try
          {
                Class.forName(driver).newInstance();
                Connection conn = (Connection) DriverManager.getConnection(url + dbName, userName, password);
                System.out.println("Database Connection Successful");

                // Set Up SQL
                String sql = "SELECT * FROM dublinzoo.records WHERE RECORD_ID LIKE ?";

                // Excute Query and send result set to rs
                prest = conn.prepareStatement(sql);
                prest.setString(1,VetIDSearch.getText());

                ResultSet rs = prest.executeQuery();

                //Retrieve by column name
                VetTable.setModel(DbUtils.resultSetToTableModel(rs));

                rs.close();
                prest.close();

                // Close the connection to the database
                conn.close();
            }
                catch (Exception e)
                {
                e.printStackTrace();
                }
            }



    }//GEN-LAST:event_VetSearchActionPerformed

    private void VetCBox1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_VetCBox1KeyPressed
    
    if (evt.getKeyCode()==java.awt.event.KeyEvent.VK_ENTER)

    if (VetCBox1.getSelectedItem().equals("animal"))
    {
    VetIDSearch.setVisible(true);
    jLabel1.setVisible(true);
    }

    else if (VetCBox1.getSelectedItem().equals("records"))
    {
    VetIDSearch.setVisible(true);
    jLabel1.setVisible(true);
    }



    }//GEN-LAST:event_VetCBox1KeyPressed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
    VetIDSearch.setVisible(false);
    jLabel1.setVisible(false);
    }//GEN-LAST:event_formWindowActivated

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
          String url = "jdbc:mysql://127.0.0.1:3306/";
          String dbName = "dublinzoo";
          String driver = "com.mysql.jdbc.Driver";
          String userName = "root";
          String password = "nss2013";
          //String password = "NSS2014";

          try
          {
          Class.forName(driver).newInstance();
          Connection conn = (Connection) DriverManager.getConnection(url + dbName, userName, password);
          System.out.println("Database Connection Successful");

          // Set Up SQL
        String sql = " UPDATE dublinzoo.animal set ANIMAL_NAME = ?, ANIMAL_TYPE = ?, "
                    + " GENDER = ?, DOB = ?, DIET_TYPE = ?, DIET = ?, STATUS = ?, HEALTH= ?, "
                    +" SPACE_REQUIRED_ACRES = ? WHERE ANIMAL_ID = ? ";

        //A.setAnimal_ID(AnimalSearchTable.getValueAt(0, 1).toString());

        A.setAnimal_Name(VetTable.getValueAt(0, 1).toString());
        A.setAnimal_Type(VetTable.getValueAt(0, 2).toString());
        A.setGender(VetTable.getValueAt(0, 3).toString());
        A.setDOB(VetTable.getValueAt(0, 4).toString());
        A.setDiet_Type(VetTable.getValueAt(0, 5).toString());
        A.setDiet(VetTable.getValueAt(0, 6).toString());
        A.setStatus(VetTable.getValueAt(0, 7).toString());
        A.setHealth(VetTable.getValueAt(0, 8).toString());
        A.setSpace_Required_Acres(Integer.parseInt(VetTable.getValueAt(0, 9).toString()));

          // Excute Query and send result set to rs
          prest = conn.prepareStatement(sql);

          //prest.setString(1, A.getAnimal_ID());

          prest.setString(1, A.getAnimal_Name());
          prest.setString(2, A.getAnimal_Type());
          prest.setString(3, A.getGender());
          prest.setString(4, A.getDOB());
          prest.setString(5, A.getDiet_Type());
          prest.setString(6, A.getDiet());
          prest.setString(7, A.getStatus());
          prest.setString(8, A.getHealth());
          prest.setInt(9, A.getSpace_Required_Acres());
          prest.setString(10, VetIDSearch.getText());
          

          prest.executeUpdate();
          JOptionPane.showMessageDialog(rootPane, "Update Successfull!");

          // Close the connection to the database
          conn.close();
          prest.close();
          }

          //catch (SQLException s)
          //{
          //System.out.println("SQL statement is not executed!");
          //JOptionPane.showMessageDialog(rootPane, "Update NOT Successfull!");
          //}

          catch (Exception e)
          {
          e.printStackTrace();
          }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       Login Frame0= new Login();
        Frame0.setVisible(true);

        setVisible(false);
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VetFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox VetCBox1;
    private javax.swing.JTextField VetIDSearch;
    private javax.swing.JButton VetSearch;
    private javax.swing.JTable VetTable;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

}
